# Generated by Django 5.0.3 on 2024-04-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_article_id_article_tengriid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DateKeeper',
        ),
        migrations.RemoveField(
            model_name='article',
            name='TengriID',
        ),
        migrations.RemoveField(
            model_name='article',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='article',
            name='viewings',
        ),
        migrations.AddField(
            model_name='article',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
